from experta import Fact

class QueryFact(Fact):
    query_type: str
    predicate_type: str
    has_subquery: bool
    has_group_by: bool
    has_order_by: bool
    has_distinct: bool
    has_limit_offset: bool
    uses_exists: bool
    uses_in: bool
    uses_not_in: bool
    uses_union: bool
    uses_union_all: bool
    select_list_wide: bool
    select_list_minimal: bool
    has_where_clause: bool
    has_having_clause: bool
    has_join_condition: bool
    has_correlated_subquery: bool
    has_aggregation: bool
    has_or_condition: bool
    number_of_tables: int
    number_of_predicates: int

class TableFact(Fact):
    relation_name: str
    tuples_count: int
    blocks_count: int
    tuple_size: int
    blocking_factor: int
    statistics_fresh: bool
    data_distribution_known: bool
    relation_fits_in_memory: bool
    distinct_values: int
    has_null_values: bool
    has_primary_key: bool
    has_foreign_key: bool
    is_small_table: bool
    is_large_table: bool
    rows_per_block: int
    total_size_mb: float
    selectivity_estimate: float
    most_selective_column: str

class IndexFact(Fact):
    relation_name: str
    column_name: str
    has_index: bool
    index_type: str
    index_selectivity_high: bool
    index_supports_join: bool
    index_supports_order_by: bool
    index_fragmented: bool
    index_unused: bool
    index_covering: bool
    index_clustered: bool
    index_nonclustered: bool
    index_on_predicate_column: bool
    index_on_join_column: bool
    index_cardinality_high: bool
    index_usage_count: int
    composite_index_exists: bool
    index_columns_count: int

class JoinFact(Fact):
    join_type: str
    join_keys_indexed: bool
    outer_relation_size: int
    inner_relation_size: int
    outer_relation_name: str
    inner_relation_name: str
    merge_join_possible: bool
    hash_join_possible: bool
    nested_loop_possible: bool
    sort_merge_cost_acceptable: bool
    hash_build_cost_acceptable: bool
    outer_relation_small: bool
    inner_relation_small: bool
    both_relations_large: bool
    one_relation_small: bool
    join_condition_equality: bool
    number_of_joins: int
    join_ordering_possible: bool

class WorkloadFact(Fact):
    need_fast_response: bool
    read_heavy_workload: bool
    write_heavy_workload: bool
    need_sorted_output: bool
    need_no_duplicates: bool
    temp_table_allowed: bool
    temporary_index_allowed: bool
    query_execution_frequency: str
    response_time_critical: bool
    batch_processing: bool
    memory_constrained: bool
    disk_space_limited: bool
    concurrent_users_high: bool

class StatsFact(Fact):
    cost_estimate_available: bool
    stats_are_outdated: bool
    estimated_rows: int
    estimated_cost: float
    intermediate_result_large: bool
    most_selective_predicate: str
    best_candidate_plan: str
    actual_execution_time_ms: float
    estimated_io_cost: float
    estimated_cpu_cost: float
    cardinality_estimate_accurate: bool
    histogram_available: bool
    sampling_freshness_pct: float

class RecommendationFact(Fact):
    recommendation_id: int
    category: str
    recommendation_text: str
    reasoning: str
    priority: str
    expected_improvement: str
    applies_to: str
