from engine.facts import *

def case_join_query():
    query = QueryFact(
        query_type="SELECT_JOIN",
        predicate_type="equality",
        has_subquery=False,
        has_group_by=False,
        has_order_by=False,
        has_distinct=False,
        has_limit_offset=False,
        uses_exists=False,
        uses_in=False,
        uses_not_in=False,
        uses_union=False,
        uses_union_all=False,
        select_list_wide=True,
        select_list_minimal=False,
        has_where_clause=True,
        has_having_clause=False,
        has_join_condition=True,
        has_correlated_subquery=False,
        has_aggregation=False,
        has_or_condition=False,
        number_of_tables=3,
        number_of_predicates=3
    )

    tables = [
        TableFact(
            relation_name="orders",
            tuples_count=500000,
            blocks_count=10000,
            tuple_size=128,
            blocking_factor=80,
            statistics_fresh=True,
            data_distribution_known=True,
            relation_fits_in_memory=False,
            distinct_values=250000,
            has_null_values=False,
            has_primary_key=True,
            has_foreign_key=True,
            is_small_table=False,
            is_large_table=True,
            rows_per_block=80,
            total_size_mb=64.0,
            selectivity_estimate=0.01,
            most_selective_column="order_id"
        ),
        TableFact(
            relation_name="customers",
            tuples_count=50000,
            blocks_count=1000,
            tuple_size=200,
            blocking_factor=50,
            statistics_fresh=True,
            data_distribution_known=True,
            relation_fits_in_memory=True,
            distinct_values=50000,
            has_null_values=False,
            has_primary_key=True,
            has_foreign_key=False,
            is_small_table=True,
            is_large_table=False,
            rows_per_block=50,
            total_size_mb=10.0,
            selectivity_estimate=0.02,
            most_selective_column="customer_id"
        ),
        TableFact(
            relation_name="products",
            tuples_count=10000,
            blocks_count=200,
            tuple_size=512,
            blocking_factor=20,
            statistics_fresh=False,
            data_distribution_known=False,
            relation_fits_in_memory=True,
            distinct_values=10000,
            has_null_values=False,
            has_primary_key=True,
            has_foreign_key=False,
            is_small_table=True,
            is_large_table=False,
            rows_per_block=20,
            total_size_mb=5.0,
            selectivity_estimate=0.1,
            most_selective_column="product_id"
        )
    ]

    indexes = [
        IndexFact(
            relation_name="orders",
            column_name="order_id",
            has_index=True,
            index_type="B+TREE",
            index_selectivity_high=True,
            index_supports_join=False,
            index_supports_order_by=True,
            index_fragmented=False,
            index_unused=False,
            index_covering=False,
            index_clustered=True,
            index_nonclustered=False,
            index_on_predicate_column=False,
            index_on_join_column=False,
            index_cardinality_high=True,
            index_usage_count=5000,
            composite_index_exists=False,
            index_columns_count=1
        ),
        IndexFact(
            relation_name="orders",
            column_name="customer_id",
            has_index=True,
            index_type="NON_CLUSTERED",
            index_selectivity_high=False,
            index_supports_join=True,
            index_supports_order_by=False,
            index_fragmented=False,
            index_unused=False,
            index_covering=False,
            index_clustered=False,
            index_nonclustered=True,
            index_on_predicate_column=False,
            index_on_join_column=True,
            index_cardinality_high=False,
            index_usage_count=200,
            composite_index_exists=False,
            index_columns_count=1
        )
    ]

    joins = [
        JoinFact(
            join_type="INNER_JOIN",
            join_keys_indexed=True,
            outer_relation_size=50000,
            inner_relation_size=500000,
            outer_relation_name="customers",
            inner_relation_name="orders",
            merge_join_possible=True,
            hash_join_possible=True,
            nested_loop_possible=True,
            sort_merge_cost_acceptable=True,
            hash_build_cost_acceptable=True,
            outer_relation_small=True,
            inner_relation_small=False,
            both_relations_large=False,
            one_relation_small=True,
            join_condition_equality=True,
            number_of_joins=2,
            join_ordering_possible=True
        ),
        JoinFact(
            join_type="INNER_JOIN",
            join_keys_indexed=False,
            outer_relation_size=10000,
            inner_relation_size=500000,
            outer_relation_name="products",
            inner_relation_name="orders",
            merge_join_possible=False,
            hash_join_possible=True,
            nested_loop_possible=True,
            sort_merge_cost_acceptable=False,
            hash_build_cost_acceptable=True,
            outer_relation_small=True,
            inner_relation_small=False,
            both_relations_large=False,
            one_relation_small=True,
            join_condition_equality=True,
            number_of_joins=2,
            join_ordering_possible=True
        )
    ]

    workload = WorkloadFact(
        need_fast_response=False,
        read_heavy_workload=True,
        write_heavy_workload=False,
        need_sorted_output=False,
        need_no_duplicates=False,
        temp_table_allowed=True,
        temporary_index_allowed=True,
        query_execution_frequency="MEDIUM",
        response_time_critical=False,
        batch_processing=True,
        memory_constrained=False,
        disk_space_limited=False,
        concurrent_users_high=False
    )

    stats = StatsFact(
        cost_estimate_available=True,
        stats_are_outdated=True,
        estimated_rows=50000,
        estimated_cost=150.0,
        intermediate_result_large=True,
        most_selective_predicate="customers.region = ?",
        best_candidate_plan="Hash Join",
        actual_execution_time_ms=3200.0,
        estimated_io_cost=100.0,
        estimated_cpu_cost=50.0,
        cardinality_estimate_accurate=False,
        histogram_available=False,
        sampling_freshness_pct=40.0
    )

    return query, tables, indexes, joins, workload, stats
